### PR TITLE
feat: drop support for Node versions 12 and 17

### PR DESCRIPTION
**Pull request by SimenB**
Like https://github.com/jest-community/eslint-plugin-jest/pull/1211

### CODE REVIEW

**Comment by G-Rath** [comment]
Don't you want to merge this into `next`?

**Comment by SimenB** [comment]
Nah, I was thinking to just land them quickly on main 🙂

**Comment by SimenB** [comment]
I just assumed there's no breaking changes we wanna make (beyond version drops)?

**Comment by G-Rath** [comment]
Yeah fair enough

**Review by G-Rath — APPROVED** [review]

**Pull request merged**
